# Generated by Django 5.2.4 on 2025-08-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_auction_user_watch_list_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
