# Generated by Django 5.2.4 on 2025-08-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highest_bidder',
        ),
        migrations.AddField(
            model_name='user',
            name='highest_bider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bidder', to='auctions.auction'),
        ),
    ]
