# Generated by Django 5.2.4 on 2025-08-07 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_highest_bidder_user_highest_bider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highest_bider',
        ),
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
