# Generated by Django 5.2.4 on 2025-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_user_highest_bider_auction_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='created_at',
        ),
    ]
